bind r new-window -n 'tmux.conf' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"Config reloaded\"'"

set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"

set -g bell-action none
set -g  synchronize-panes

set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

setw -g monitor-activity on
set -g visual-activity on

set -g window-status-current-attr "underscore"
set -g set-titles on
set -g set-titles-string "#I:#W"

set -g status on
set -g status-interval 15
set -g status-justify left
set -g status-keys vi
set -g status-position bottom
set -g status-style fg=white,bg="#005faf"

set -g status-left "[#S] "
set -g status-left-length 10
set -g status-left-style default

set -g status-right "#(~/.config/tmux/right.sh)"
set -g status-right-length 800
set -g status-right-style default

set-option -g message-bg black #base02
set-option -g message-fg brightred #orange

%if #{TMUX}
set -g status-bg red
%endif
