services:
  box:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    entrypoint:
      - sleep
    command:
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 127.0.0.1:8080:8080
